import { Frase } from '../shared/frase.model'

const FRASES: Frase[] = [
  { fraseEnglish: 'I Like to Learn', frasePortuguese: 'Eu gosto de aprender' },
  { fraseEnglish: 'I Love You', frasePortuguese: 'Eu Te Amo' },
  { fraseEnglish: 'Hello', frasePortuguese: 'Olá' },
  { fraseEnglish: 'Goodbye', frasePortuguese: 'Adeus' },
  { fraseEnglish: 'Yes', frasePortuguese: 'Sim' },
  { fraseEnglish: 'No', frasePortuguese: 'Não' },
  { fraseEnglish: 'Thank You', frasePortuguese: 'Obrigado' },
  { fraseEnglish: 'You re Welcome', frasePortuguese: 'De Nada' },
  { fraseEnglish: 'Excuse Me', frasePortuguese: 'Com Licença' },
  { fraseEnglish: 'I m Sorry', frasePortuguese: 'Desculpe' },
  { fraseEnglish: 'How Are You?', frasePortuguese: 'Como você está?' },
  { fraseEnglish: 'I m Fine, Thanks', frasePortuguese: 'Estou bem, obrigado' },
  { fraseEnglish: "What's Your Name?", frasePortuguese: 'Qual é o seu nome?' },
  { fraseEnglish: 'My Name is...', frasePortuguese: 'Meu nome é...' },
  { fraseEnglish: 'Nice to Meet You', frasePortuguese: 'Prazer em conhecê-lo' },
  { fraseEnglish: 'How old are you?', frasePortuguese: 'Quantos anos você tem?' },
  { fraseEnglish: 'I am ... years old', frasePortuguese: 'Eu tenho ... anos' },
  { fraseEnglish: 'Where are you from?', frasePortuguese: 'De onde você é?' },
  { fraseEnglish: 'I am from...', frasePortuguese: 'Eu sou de...' },
  { fraseEnglish: 'Do you speak English?', frasePortuguese: 'Você fala inglês?' },
  { fraseEnglish: 'I speak a little English', frasePortuguese: 'Eu falo um pouco de inglês' },
  { fraseEnglish: 'What do you do for a living?', frasePortuguese: 'O que você faz para viver?' },
  { fraseEnglish: 'I work as a...', frasePortuguese: 'Eu trabalho como...' },
  { fraseEnglish: 'Do you like it?', frasePortuguese: 'Você gosta disso?' },
  { fraseEnglish: 'I love it', frasePortuguese: 'Eu amo isso' },
  { fraseEnglish: 'I hate it', frasePortuguese: 'Eu odeio isso' },
  { fraseEnglish: 'Can you help me?', frasePortuguese: 'Você pode me ajudar?' },
  { fraseEnglish: 'Of course, what do you need?', frasePortuguese: 'Claro, o que você precisa?' },
  { fraseEnglish: 'Where is the nearest...', frasePortuguese: 'Onde fica o mais próximo...' },
  { fraseEnglish: 'Can you show me on the map?', frasePortuguese: 'Você pode me mostrar no mapa?' },
  { fraseEnglish: 'Do you need anything else?', frasePortuguese: 'Você precisa de mais alguma coisa?' },
  { fraseEnglish: 'That will be all, thank you', frasePortuguese: 'Isso será tudo, obrigado' },
  { fraseEnglish: 'What time is it?', frasePortuguese: 'Que horas são?' },
  { fraseEnglish: 'It s ...o clock', frasePortuguese: 'São ... horas' },
  { fraseEnglish: 'How much does it cost?', frasePortuguese: 'Quanto custa isso?' }
]
